import { InMemoryDbService } from 'angular-in-memory-web-api';

import { Category } from './pages/categories/shared/category.model';
import { Entry } from './pages/entries/shared/entry.model';

export class InMemoryDatabase implements InMemoryDbService {
  createDb() {
    const categories: Category[] = [
      { id: 1, name: 'Moradia', description: 'Pagamentos de Contas da Casa' },
      { id: 2, name: 'Saúde', description: 'Plano de Saúde e Remédios' },
      { id: 3, name: 'Lazer', description: 'Cinema, parques, praia, etc' },
      { id: 4, name: 'Salário', description: 'Recebimento de Salário' },
      { id: 5, name: 'Freelas', description: 'Trabalhos como freelancer' },
    ];

    const entries: Entry[] = [
      {
        id: 1,
        name: 'Gás de Cozinha',
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: '2018-11-15',
        amount: 70.80,
        type: 'expense',
        description: 'Qualquer descrição para essa despesa',
      } as Entry,
      {
        id: 2,
        name: 'Suplementos',
        categoryId: categories[1].id,
        category: categories[1],
        paid: false,
        date: '2018-11-18',
        amount: 15.00,
        type: 'expense',
      } as Entry,
      {
        id: 3,
        name: 'Salário na Empresa X',
        categoryId: categories[3].id,
        category: categories[3],
        paid: true,
        date: '2020-02-22',
        amount: 4405.49,
        type: 'revenue',
      } as Entry,
      {
        id: 4,
        name: 'Aluguel de Filme',
        categoryId: categories[2].id,
        category: categories[2],
        paid: true,
        date: '2019-01-09',
        amount: 15.00,
        type: 'expense',
      } as Entry,
      {
        id: 5,
        name: 'Suplementos',
        categoryId: categories[1].id,
        category: categories[1],
        paid: true,
        date: '2017-10-11',
        amount: 30.00,
        type: 'expense',
      } as Entry,
      {
        id: 6,
        name: 'Video Game da Filha',
        categoryId: categories[2].id,
        category: categories[2],
        paid: false,
        date: '2020-09-21',
        amount: 15.00,
        type: 'expense',
      } as Entry,
      {
        id: 11,
        name: 'Uber',
        categoryId: categories[1].id,
        category: categories[1],
        paid: true,
        date: '2018-10-30',
        amount: 30.00,
        type: 'expense',
      } as Entry,
      {
        id: 12,
        name: 'Aluguel',
        categoryId: categories[2].id,
        category: categories[2],
        paid: false,
        date: '2018-05-28',
        amount: 15.00,
        type: 'revenue',
      } as Entry,
      {
        id: 13,
        name: 'Gás de Cozinha',
        categoryId: categories[1].id,
        category: categories[1],
        paid: false,
        date: '2022-04-03',
        amount: 30.00,
        type: 'expense',
      } as Entry,
      {
        id: 14,
        name: 'Pagamento Pelo Projeto XYZ',
        categoryId: categories[4].id,
        category: categories[4],
        paid: true,
        date: '2018-11-19',
        amount: 2980.00,
        type: 'revenue',
      } as Entry,
      {
        id: 19,
        name: 'Aluguel de Filme',
        categoryId: categories[2].id,
        category: categories[2],
        paid: false,
        date: '2020-03-17',
        amount: 15.00,
        type: 'expense',
      } as Entry,
      {
        id: 21,
        name: 'Video Game da Filha',
        categoryId: categories[1].id,
        category: categories[1],
        paid: true,
        date: '2020-12-06',
        amount: 30.00,
        type: 'expense',
      } as Entry,
      {
        id: 22,
        name: 'Cinema',
        categoryId: categories[2].id,
        category: categories[2],
        paid: true,
        date: '2017-10-10',
        amount: 15.00,
        type: 'expense',
      } as Entry,
      {
        id: 23,
        name: 'Jiu Jitsu',
        categoryId: categories[1].id,
        category: categories[1],
        paid: false,
        date: '2019-11-02',
        amount: 130.00,
        type: 'expense',
      } as Entry,
      {
        id: 44,
        name: 'Uber',
        categoryId: categories[2].id,
        category: categories[2],
        paid: true,
        date: '2017-10-05',
        amount: 15.00,
        type: 'expense',
      } as Entry,
      {
        id: 55,
        name: 'Cinema',
        categoryId: categories[1].id,
        category: categories[1],
        paid: false,
        date: '2019-10-25',
        amount: 30.00,
        type: 'expense',
      } as Entry,
    ];

    return { categories, entries };
  }
}
